apiVersion: catalogv2.rancher.m.openplatform.suse.com/v1alpha1
kind: V2
metadata:
  annotations:
    meta.upbound.io/example-id: catalogv2/v1alpha1/v2
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    gitBranch: <GIT_BRANCH>
    gitRepo: <GIT_REPO_URL>
