//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitInitParameters) DeepCopyInto(out *ContainerResourceLimitInitParameters) {
	*out = *in
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitInitParameters.
func (in *ContainerResourceLimitInitParameters) DeepCopy() *ContainerResourceLimitInitParameters {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitObservation) DeepCopyInto(out *ContainerResourceLimitObservation) {
	*out = *in
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitObservation.
func (in *ContainerResourceLimitObservation) DeepCopy() *ContainerResourceLimitObservation {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitParameters) DeepCopyInto(out *ContainerResourceLimitParameters) {
	*out = *in
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitParameters.
func (in *ContainerResourceLimitParameters) DeepCopy() *ContainerResourceLimitParameters {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitInitParameters) DeepCopyInto(out *LimitInitParameters) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitInitParameters.
func (in *LimitInitParameters) DeepCopy() *LimitInitParameters {
	if in == nil {
		return nil
	}
	out := new(LimitInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitObservation) DeepCopyInto(out *LimitObservation) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitObservation.
func (in *LimitObservation) DeepCopy() *LimitObservation {
	if in == nil {
		return nil
	}
	out := new(LimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitParameters) DeepCopyInto(out *LimitParameters) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitParameters.
func (in *LimitParameters) DeepCopy() *LimitParameters {
	if in == nil {
		return nil
	}
	out := new(LimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Namespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceInitParameters) DeepCopyInto(out *NamespaceInitParameters) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ContainerResourceLimit != nil {
		in, out := &in.ContainerResourceLimit, &out.ContainerResourceLimit
		*out = make([]ContainerResourceLimitInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = make([]ResourceQuotaInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitForCluster != nil {
		in, out := &in.WaitForCluster, &out.WaitForCluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceInitParameters.
func (in *NamespaceInitParameters) DeepCopy() *NamespaceInitParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceList) DeepCopyInto(out *NamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Namespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceList.
func (in *NamespaceList) DeepCopy() *NamespaceList {
	if in == nil {
		return nil
	}
	out := new(NamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceObservation) DeepCopyInto(out *NamespaceObservation) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ContainerResourceLimit != nil {
		in, out := &in.ContainerResourceLimit, &out.ContainerResourceLimit
		*out = make([]ContainerResourceLimitObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = make([]ResourceQuotaObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitForCluster != nil {
		in, out := &in.WaitForCluster, &out.WaitForCluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceObservation.
func (in *NamespaceObservation) DeepCopy() *NamespaceObservation {
	if in == nil {
		return nil
	}
	out := new(NamespaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceParameters) DeepCopyInto(out *NamespaceParameters) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ContainerResourceLimit != nil {
		in, out := &in.ContainerResourceLimit, &out.ContainerResourceLimit
		*out = make([]ContainerResourceLimitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = make([]ResourceQuotaParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitForCluster != nil {
		in, out := &in.WaitForCluster, &out.WaitForCluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceParameters.
func (in *NamespaceParameters) DeepCopy() *NamespaceParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSpec) DeepCopyInto(out *NamespaceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSpec.
func (in *NamespaceSpec) DeepCopy() *NamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceStatus) DeepCopyInto(out *NamespaceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceStatus.
func (in *NamespaceStatus) DeepCopy() *NamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaInitParameters) DeepCopyInto(out *ResourceQuotaInitParameters) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = make([]LimitInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaInitParameters.
func (in *ResourceQuotaInitParameters) DeepCopy() *ResourceQuotaInitParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaObservation) DeepCopyInto(out *ResourceQuotaObservation) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = make([]LimitObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaObservation.
func (in *ResourceQuotaObservation) DeepCopy() *ResourceQuotaObservation {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaParameters) DeepCopyInto(out *ResourceQuotaParameters) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = make([]LimitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaParameters.
func (in *ResourceQuotaParameters) DeepCopy() *ResourceQuotaParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaParameters)
	in.DeepCopyInto(out)
	return out
}
