// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ContainerResourceLimitInitParameters struct {

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`
}

type ContainerResourceLimitObservation struct {

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`
}

type ContainerResourceLimitParameters struct {

	// CPU limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// CPU reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`
}

type LimitInitParameters struct {

	// Limit for config maps in namespace (string)
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in namespace (string)
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in namespace (string)
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in namespace (string)
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in namespace (string)
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in namespace (string)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in namespace (string)
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in namespace (string)
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type LimitObservation struct {

	// Limit for config maps in namespace (string)
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in namespace (string)
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in namespace (string)
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in namespace (string)
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in namespace (string)
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in namespace (string)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in namespace (string)
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in namespace (string)
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type LimitParameters struct {

	// Limit for config maps in namespace (string)
	// +kubebuilder:validation:Optional
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in namespace (string)
	// +kubebuilder:validation:Optional
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in namespace (string)
	// +kubebuilder:validation:Optional
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in namespace (string)
	// +kubebuilder:validation:Optional
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in namespace (string)
	// +kubebuilder:validation:Optional
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in namespace (string)
	// +kubebuilder:validation:Optional
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// +kubebuilder:validation:Optional
	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in namespace (string)
	// +kubebuilder:validation:Optional
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in namespace (string)
	// +kubebuilder:validation:Optional
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type NamespaceInitParameters struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Default containers resource limits on namespace (List maxitem:1)
	ContainerResourceLimit []ContainerResourceLimitInitParameters `json:"containerResourceLimit,omitempty" tf:"container_resource_limit,omitempty"`

	// A namespace description (string)
	// Description of the k8s namespace managed by rancher v2
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The project id where assign namespace. It's on the form project_id=<cluster_id>:<id>. Updating <id> part on same <cluster_id> namespace will be moved between projects (string)
	// Project ID where k8s namespace belongs
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/namespaced/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Resource quota for namespace. Rancher v2.1.x or higher (list maxitems:1)
	ResourceQuota []ResourceQuotaInitParameters `json:"resourceQuota,omitempty" tf:"resource_quota,omitempty"`

	// Wait for cluster becomes active. Default false (bool)
	// Wait for cluster becomes active
	WaitForCluster *bool `json:"waitForCluster,omitempty" tf:"wait_for_cluster,omitempty"`
}

type NamespaceObservation struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Default containers resource limits on namespace (List maxitem:1)
	ContainerResourceLimit []ContainerResourceLimitObservation `json:"containerResourceLimit,omitempty" tf:"container_resource_limit,omitempty"`

	// A namespace description (string)
	// Description of the k8s namespace managed by rancher v2
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The project id where assign namespace. It's on the form project_id=<cluster_id>:<id>. Updating <id> part on same <cluster_id> namespace will be moved between projects (string)
	// Project ID where k8s namespace belongs
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Resource quota for namespace. Rancher v2.1.x or higher (list maxitems:1)
	ResourceQuota []ResourceQuotaObservation `json:"resourceQuota,omitempty" tf:"resource_quota,omitempty"`

	// Wait for cluster becomes active. Default false (bool)
	// Wait for cluster becomes active
	WaitForCluster *bool `json:"waitForCluster,omitempty" tf:"wait_for_cluster,omitempty"`
}

type NamespaceParameters struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Default containers resource limits on namespace (List maxitem:1)
	// +kubebuilder:validation:Optional
	ContainerResourceLimit []ContainerResourceLimitParameters `json:"containerResourceLimit,omitempty" tf:"container_resource_limit,omitempty"`

	// A namespace description (string)
	// Description of the k8s namespace managed by rancher v2
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The project id where assign namespace. It's on the form project_id=<cluster_id>:<id>. Updating <id> part on same <cluster_id> namespace will be moved between projects (string)
	// Project ID where k8s namespace belongs
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Resource quota for namespace. Rancher v2.1.x or higher (list maxitems:1)
	// +kubebuilder:validation:Optional
	ResourceQuota []ResourceQuotaParameters `json:"resourceQuota,omitempty" tf:"resource_quota,omitempty"`

	// Wait for cluster becomes active. Default false (bool)
	// Wait for cluster becomes active
	// +kubebuilder:validation:Optional
	WaitForCluster *bool `json:"waitForCluster,omitempty" tf:"wait_for_cluster,omitempty"`
}

type ResourceQuotaInitParameters struct {

	// Resource quota limit for namespace (list maxitems:1)
	Limit []LimitInitParameters `json:"limit,omitempty" tf:"limit,omitempty"`
}

type ResourceQuotaObservation struct {

	// Resource quota limit for namespace (list maxitems:1)
	Limit []LimitObservation `json:"limit,omitempty" tf:"limit,omitempty"`
}

type ResourceQuotaParameters struct {

	// Resource quota limit for namespace (list maxitems:1)
	// +kubebuilder:validation:Optional
	Limit []LimitParameters `json:"limit" tf:"limit,omitempty"`
}

// NamespaceSpec defines the desired state of Namespace
type NamespaceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NamespaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NamespaceInitParameters `json:"initProvider,omitempty"`
}

// NamespaceStatus defines the observed state of Namespace.
type NamespaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NamespaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Namespace is the Schema for the Namespaces API. "Managed resource"page_title: "rancher2_namespace Resource"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher}
type Namespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   NamespaceSpec   `json:"spec"`
	Status NamespaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NamespaceList contains a list of Namespaces
type NamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Namespace `json:"items"`
}

// Repository type metadata.
var (
	Namespace_Kind             = "Namespace"
	Namespace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Namespace_Kind}.String()
	Namespace_KindAPIVersion   = Namespace_Kind + "." + CRDGroupVersion.String()
	Namespace_GroupVersionKind = CRDGroupVersion.WithKind(Namespace_Kind)
)

func init() {
	SchemeBuilder.Register(&Namespace{}, &NamespaceList{})
}
