// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type V2InitParameters struct {

	// Annotations for the catalog v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// CA certificate in base64-encoded DER format which will be used to validate the repo's certificate (string)
	// CA certificate in base64-encoded DER format which will be used to validate the repo's certificate
	CABundle *string `json:"caBundle,omitempty" tf:"ca_bundle,omitempty"`

	// The cluster id of the catalog V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/namespaced/cluster/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// If disabled the repo clone will not be updated or allowed to be installed from. Default: true (bool)
	// If disabled the repo clone will not be updated or allowed to be installed from
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Maximum number of retries before returning error
	ExponentialBackoffMaxRetries *float64 `json:"exponentialBackoffMaxRetries,omitempty" tf:"exponential_backoff_max_retries,omitempty"`

	// Maximum amount of seconds to wait before retrying
	ExponentialBackoffMaxWait *float64 `json:"exponentialBackoffMaxWait,omitempty" tf:"exponential_backoff_max_wait,omitempty"`

	// Minimum amount of seconds to wait before retrying
	ExponentialBackoffMinWait *float64 `json:"exponentialBackoffMinWait,omitempty" tf:"exponential_backoff_min_wait,omitempty"`

	// Git Repository branch containing Helm chart definitions. Default master (string)
	// Git Repository branch containing Helm chart definitions
	GitBranch *string `json:"gitBranch,omitempty" tf:"git_branch,omitempty"`

	// The url of the catalog v2 repo. Conflicts with url (string)
	// Git Repository containing Helm chart definitions
	GitRepo *string `json:"gitRepo,omitempty" tf:"git_repo,omitempty"`

	// Use insecure HTTPS to download the repo's index. Default: false (bool)
	// Use insecure HTTPS to download the repo's index
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// Only valid for OCI URL's. Allows insecure connections to registries without enforcing TLS checks
	InsecurePlainHTTP *bool `json:"insecurePlainHttp,omitempty" tf:"insecure_plain_http,omitempty"`

	// Labels for the catalog v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// K8s secret name to be used to connect to the repo (string)
	// K8s secret name to be used to connect to the repo
	SecretName *string `json:"secretName,omitempty" tf:"secret_name,omitempty"`

	// K8s secret namespace (string)
	// K8s secret namespace
	SecretNamespace *string `json:"secretNamespace,omitempty" tf:"secret_namespace,omitempty"`

	// K8s service account used to deploy charts instead of the end users credentials (string)
	// K8s service account used to deploy charts instead of the end users credentials
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// The username to access the catalog if needed (string)
	// K8s namsepace of the service account
	ServiceAccountNamespace *string `json:"serviceAccountNamespace,omitempty" tf:"service_account_namespace,omitempty"`

	// URL to an index generated by Helm. Conflicts with git_repo (string)
	// URL to an index generated by Helm
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type V2Observation struct {

	// Annotations for the catalog v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// CA certificate in base64-encoded DER format which will be used to validate the repo's certificate (string)
	// CA certificate in base64-encoded DER format which will be used to validate the repo's certificate
	CABundle *string `json:"caBundle,omitempty" tf:"ca_bundle,omitempty"`

	// The cluster id of the catalog V2 (string)
	// K8s cluster ID
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// If disabled the repo clone will not be updated or allowed to be installed from. Default: true (bool)
	// If disabled the repo clone will not be updated or allowed to be installed from
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Maximum number of retries before returning error
	ExponentialBackoffMaxRetries *float64 `json:"exponentialBackoffMaxRetries,omitempty" tf:"exponential_backoff_max_retries,omitempty"`

	// Maximum amount of seconds to wait before retrying
	ExponentialBackoffMaxWait *float64 `json:"exponentialBackoffMaxWait,omitempty" tf:"exponential_backoff_max_wait,omitempty"`

	// Minimum amount of seconds to wait before retrying
	ExponentialBackoffMinWait *float64 `json:"exponentialBackoffMinWait,omitempty" tf:"exponential_backoff_min_wait,omitempty"`

	// Git Repository branch containing Helm chart definitions. Default master (string)
	// Git Repository branch containing Helm chart definitions
	GitBranch *string `json:"gitBranch,omitempty" tf:"git_branch,omitempty"`

	// The url of the catalog v2 repo. Conflicts with url (string)
	// Git Repository containing Helm chart definitions
	GitRepo *string `json:"gitRepo,omitempty" tf:"git_repo,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Use insecure HTTPS to download the repo's index. Default: false (bool)
	// Use insecure HTTPS to download the repo's index
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// Only valid for OCI URL's. Allows insecure connections to registries without enforcing TLS checks
	InsecurePlainHTTP *bool `json:"insecurePlainHttp,omitempty" tf:"insecure_plain_http,omitempty"`

	// Labels for the catalog v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Computed) The k8s resource version (string)
	ResourceVersion *string `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// K8s secret name to be used to connect to the repo (string)
	// K8s secret name to be used to connect to the repo
	SecretName *string `json:"secretName,omitempty" tf:"secret_name,omitempty"`

	// K8s secret namespace (string)
	// K8s secret namespace
	SecretNamespace *string `json:"secretNamespace,omitempty" tf:"secret_namespace,omitempty"`

	// K8s service account used to deploy charts instead of the end users credentials (string)
	// K8s service account used to deploy charts instead of the end users credentials
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// The username to access the catalog if needed (string)
	// K8s namsepace of the service account
	ServiceAccountNamespace *string `json:"serviceAccountNamespace,omitempty" tf:"service_account_namespace,omitempty"`

	// URL to an index generated by Helm. Conflicts with git_repo (string)
	// URL to an index generated by Helm
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type V2Parameters struct {

	// Annotations for the catalog v2 (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// CA certificate in base64-encoded DER format which will be used to validate the repo's certificate (string)
	// CA certificate in base64-encoded DER format which will be used to validate the repo's certificate
	// +kubebuilder:validation:Optional
	CABundle *string `json:"caBundle,omitempty" tf:"ca_bundle,omitempty"`

	// The cluster id of the catalog V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/namespaced/cluster/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// If disabled the repo clone will not be updated or allowed to be installed from. Default: true (bool)
	// If disabled the repo clone will not be updated or allowed to be installed from
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Maximum number of retries before returning error
	// +kubebuilder:validation:Optional
	ExponentialBackoffMaxRetries *float64 `json:"exponentialBackoffMaxRetries,omitempty" tf:"exponential_backoff_max_retries,omitempty"`

	// Maximum amount of seconds to wait before retrying
	// +kubebuilder:validation:Optional
	ExponentialBackoffMaxWait *float64 `json:"exponentialBackoffMaxWait,omitempty" tf:"exponential_backoff_max_wait,omitempty"`

	// Minimum amount of seconds to wait before retrying
	// +kubebuilder:validation:Optional
	ExponentialBackoffMinWait *float64 `json:"exponentialBackoffMinWait,omitempty" tf:"exponential_backoff_min_wait,omitempty"`

	// Git Repository branch containing Helm chart definitions. Default master (string)
	// Git Repository branch containing Helm chart definitions
	// +kubebuilder:validation:Optional
	GitBranch *string `json:"gitBranch,omitempty" tf:"git_branch,omitempty"`

	// The url of the catalog v2 repo. Conflicts with url (string)
	// Git Repository containing Helm chart definitions
	// +kubebuilder:validation:Optional
	GitRepo *string `json:"gitRepo,omitempty" tf:"git_repo,omitempty"`

	// Use insecure HTTPS to download the repo's index. Default: false (bool)
	// Use insecure HTTPS to download the repo's index
	// +kubebuilder:validation:Optional
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// Only valid for OCI URL's. Allows insecure connections to registries without enforcing TLS checks
	// +kubebuilder:validation:Optional
	InsecurePlainHTTP *bool `json:"insecurePlainHttp,omitempty" tf:"insecure_plain_http,omitempty"`

	// Labels for the catalog v2 (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// K8s secret name to be used to connect to the repo (string)
	// K8s secret name to be used to connect to the repo
	// +kubebuilder:validation:Optional
	SecretName *string `json:"secretName,omitempty" tf:"secret_name,omitempty"`

	// K8s secret namespace (string)
	// K8s secret namespace
	// +kubebuilder:validation:Optional
	SecretNamespace *string `json:"secretNamespace,omitempty" tf:"secret_namespace,omitempty"`

	// K8s service account used to deploy charts instead of the end users credentials (string)
	// K8s service account used to deploy charts instead of the end users credentials
	// +kubebuilder:validation:Optional
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// The username to access the catalog if needed (string)
	// K8s namsepace of the service account
	// +kubebuilder:validation:Optional
	ServiceAccountNamespace *string `json:"serviceAccountNamespace,omitempty" tf:"service_account_namespace,omitempty"`

	// URL to an index generated by Helm. Conflicts with git_repo (string)
	// URL to an index generated by Helm
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// V2Spec defines the desired state of V2
type V2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            V2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider V2InitParameters `json:"initProvider,omitempty"`
}

// V2Status defines the observed state of V2.
type V2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        V2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// V2 is the Schema for the V2s API. "Managed resource"page_title: "Rancher2: rancher2_catalog_v2 Resource"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher}
type V2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	Spec   V2Spec   `json:"spec"`
	Status V2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// V2List contains a list of V2s
type V2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []V2 `json:"items"`
}

// Repository type metadata.
var (
	V2_Kind             = "V2"
	V2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: V2_Kind}.String()
	V2_KindAPIVersion   = V2_Kind + "." + CRDGroupVersion.String()
	V2_GroupVersionKind = CRDGroupVersion.WithKind(V2_Kind)
)

func init() {
	SchemeBuilder.Register(&V2{}, &V2List{})
}
