//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitInitParameters) DeepCopyInto(out *ContainerResourceLimitInitParameters) {
	*out = *in
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitInitParameters.
func (in *ContainerResourceLimitInitParameters) DeepCopy() *ContainerResourceLimitInitParameters {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitObservation) DeepCopyInto(out *ContainerResourceLimitObservation) {
	*out = *in
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitObservation.
func (in *ContainerResourceLimitObservation) DeepCopy() *ContainerResourceLimitObservation {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceLimitParameters) DeepCopyInto(out *ContainerResourceLimitParameters) {
	*out = *in
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceLimitParameters.
func (in *ContainerResourceLimitParameters) DeepCopy() *ContainerResourceLimitParameters {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceLimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceDefaultLimitInitParameters) DeepCopyInto(out *NamespaceDefaultLimitInitParameters) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceDefaultLimitInitParameters.
func (in *NamespaceDefaultLimitInitParameters) DeepCopy() *NamespaceDefaultLimitInitParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceDefaultLimitInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceDefaultLimitObservation) DeepCopyInto(out *NamespaceDefaultLimitObservation) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceDefaultLimitObservation.
func (in *NamespaceDefaultLimitObservation) DeepCopy() *NamespaceDefaultLimitObservation {
	if in == nil {
		return nil
	}
	out := new(NamespaceDefaultLimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceDefaultLimitParameters) DeepCopyInto(out *NamespaceDefaultLimitParameters) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceDefaultLimitParameters.
func (in *NamespaceDefaultLimitParameters) DeepCopy() *NamespaceDefaultLimitParameters {
	if in == nil {
		return nil
	}
	out := new(NamespaceDefaultLimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitParameters) DeepCopyInto(out *ProjectInitParameters) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.ContainerResourceLimit != nil {
		in, out := &in.ContainerResourceLimit, &out.ContainerResourceLimit
		*out = make([]ContainerResourceLimitInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = make([]ResourceQuotaInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitForCluster != nil {
		in, out := &in.WaitForCluster, &out.WaitForCluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitParameters.
func (in *ProjectInitParameters) DeepCopy() *ProjectInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectLimitInitParameters) DeepCopyInto(out *ProjectLimitInitParameters) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectLimitInitParameters.
func (in *ProjectLimitInitParameters) DeepCopy() *ProjectLimitInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectLimitInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectLimitObservation) DeepCopyInto(out *ProjectLimitObservation) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectLimitObservation.
func (in *ProjectLimitObservation) DeepCopy() *ProjectLimitObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectLimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectLimitParameters) DeepCopyInto(out *ProjectLimitParameters) {
	*out = *in
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(string)
		**out = **in
	}
	if in.LimitsCPU != nil {
		in, out := &in.LimitsCPU, &out.LimitsCPU
		*out = new(string)
		**out = **in
	}
	if in.LimitsMemory != nil {
		in, out := &in.LimitsMemory, &out.LimitsMemory
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(string)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(string)
		**out = **in
	}
	if in.RequestsCPU != nil {
		in, out := &in.RequestsCPU, &out.RequestsCPU
		*out = new(string)
		**out = **in
	}
	if in.RequestsMemory != nil {
		in, out := &in.RequestsMemory, &out.RequestsMemory
		*out = new(string)
		**out = **in
	}
	if in.RequestsStorage != nil {
		in, out := &in.RequestsStorage, &out.RequestsStorage
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(string)
		**out = **in
	}
	if in.ServicesLoadBalancers != nil {
		in, out := &in.ServicesLoadBalancers, &out.ServicesLoadBalancers
		*out = new(string)
		**out = **in
	}
	if in.ServicesNodePorts != nil {
		in, out := &in.ServicesNodePorts, &out.ServicesNodePorts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectLimitParameters.
func (in *ProjectLimitParameters) DeepCopy() *ProjectLimitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectLimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectObservation) DeepCopyInto(out *ProjectObservation) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.ContainerResourceLimit != nil {
		in, out := &in.ContainerResourceLimit, &out.ContainerResourceLimit
		*out = make([]ContainerResourceLimitObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = make([]ResourceQuotaObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitForCluster != nil {
		in, out := &in.WaitForCluster, &out.WaitForCluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectObservation.
func (in *ProjectObservation) DeepCopy() *ProjectObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectParameters) DeepCopyInto(out *ProjectParameters) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.ContainerResourceLimit != nil {
		in, out := &in.ContainerResourceLimit, &out.ContainerResourceLimit
		*out = make([]ContainerResourceLimitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = make([]ResourceQuotaParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WaitForCluster != nil {
		in, out := &in.WaitForCluster, &out.WaitForCluster
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectParameters.
func (in *ProjectParameters) DeepCopy() *ProjectParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaInitParameters) DeepCopyInto(out *ResourceQuotaInitParameters) {
	*out = *in
	if in.NamespaceDefaultLimit != nil {
		in, out := &in.NamespaceDefaultLimit, &out.NamespaceDefaultLimit
		*out = make([]NamespaceDefaultLimitInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProjectLimit != nil {
		in, out := &in.ProjectLimit, &out.ProjectLimit
		*out = make([]ProjectLimitInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaInitParameters.
func (in *ResourceQuotaInitParameters) DeepCopy() *ResourceQuotaInitParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaObservation) DeepCopyInto(out *ResourceQuotaObservation) {
	*out = *in
	if in.NamespaceDefaultLimit != nil {
		in, out := &in.NamespaceDefaultLimit, &out.NamespaceDefaultLimit
		*out = make([]NamespaceDefaultLimitObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProjectLimit != nil {
		in, out := &in.ProjectLimit, &out.ProjectLimit
		*out = make([]ProjectLimitObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaObservation.
func (in *ResourceQuotaObservation) DeepCopy() *ResourceQuotaObservation {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaParameters) DeepCopyInto(out *ResourceQuotaParameters) {
	*out = *in
	if in.NamespaceDefaultLimit != nil {
		in, out := &in.NamespaceDefaultLimit, &out.NamespaceDefaultLimit
		*out = make([]NamespaceDefaultLimitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProjectLimit != nil {
		in, out := &in.ProjectLimit, &out.ProjectLimit
		*out = make([]ProjectLimitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaParameters.
func (in *ResourceQuotaParameters) DeepCopy() *ResourceQuotaParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaParameters)
	in.DeepCopyInto(out)
	return out
}
