// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ContainerResourceLimitInitParameters struct {

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`
}

type ContainerResourceLimitObservation struct {

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`
}

type ContainerResourceLimitParameters struct {

	// CPU limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// CPU reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`
}

type NamespaceDefaultLimitInitParameters struct {

	// Limit for config maps in project (string)
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in project (string)
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in project (string)
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in project (string)
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in project (string)
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in project (string)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in project (string)
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in project (string)
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type NamespaceDefaultLimitObservation struct {

	// Limit for config maps in project (string)
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in project (string)
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in project (string)
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in project (string)
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in project (string)
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in project (string)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in project (string)
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in project (string)
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type NamespaceDefaultLimitParameters struct {

	// Limit for config maps in project (string)
	// +kubebuilder:validation:Optional
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in project (string)
	// +kubebuilder:validation:Optional
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in project (string)
	// +kubebuilder:validation:Optional
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in project (string)
	// +kubebuilder:validation:Optional
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in project (string)
	// +kubebuilder:validation:Optional
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in project (string)
	// +kubebuilder:validation:Optional
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// +kubebuilder:validation:Optional
	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in project (string)
	// +kubebuilder:validation:Optional
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in project (string)
	// +kubebuilder:validation:Optional
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type ProjectInitParameters struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id where create project (string)
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/cluster/cluster/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Default containers resource limits on project (List maxitem:1)
	ContainerResourceLimit []ContainerResourceLimitInitParameters `json:"containerResourceLimit,omitempty" tf:"container_resource_limit,omitempty"`

	// A project description (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Resource quota for project. Rancher v2.1.x or higher (list maxitems:1)
	ResourceQuota []ResourceQuotaInitParameters `json:"resourceQuota,omitempty" tf:"resource_quota,omitempty"`

	// Wait for cluster becomes active. Default false (bool)
	// Wait for cluster becomes active
	WaitForCluster *bool `json:"waitForCluster,omitempty" tf:"wait_for_cluster,omitempty"`
}

type ProjectLimitInitParameters struct {

	// Limit for config maps in project (string)
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in project (string)
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in project (string)
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in project (string)
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in project (string)
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in project (string)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in project (string)
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in project (string)
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type ProjectLimitObservation struct {

	// Limit for config maps in project (string)
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in project (string)
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in project (string)
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in project (string)
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in project (string)
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in project (string)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in project (string)
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in project (string)
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type ProjectLimitParameters struct {

	// Limit for config maps in project (string)
	// +kubebuilder:validation:Optional
	ConfigMaps *string `json:"configMaps,omitempty" tf:"config_maps,omitempty"`

	// CPU limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsCPU *string `json:"limitsCpu,omitempty" tf:"limits_cpu,omitempty"`

	// Memory limit for containers (string)
	// +kubebuilder:validation:Optional
	LimitsMemory *string `json:"limitsMemory,omitempty" tf:"limits_memory,omitempty"`

	// Limit for persistent volume claims in project (string)
	// +kubebuilder:validation:Optional
	PersistentVolumeClaims *string `json:"persistentVolumeClaims,omitempty" tf:"persistent_volume_claims,omitempty"`

	// Limit for pods in project (string)
	// +kubebuilder:validation:Optional
	Pods *string `json:"pods,omitempty" tf:"pods,omitempty"`

	// Limit for replication controllers in project (string)
	// +kubebuilder:validation:Optional
	ReplicationControllers *string `json:"replicationControllers,omitempty" tf:"replication_controllers,omitempty"`

	// CPU reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsCPU *string `json:"requestsCpu,omitempty" tf:"requests_cpu,omitempty"`

	// Memory reservation for containers (string)
	// +kubebuilder:validation:Optional
	RequestsMemory *string `json:"requestsMemory,omitempty" tf:"requests_memory,omitempty"`

	// Limit for requests storage in project (string)
	// +kubebuilder:validation:Optional
	RequestsStorage *string `json:"requestsStorage,omitempty" tf:"requests_storage,omitempty"`

	// Limit for secrets in project (string)
	// +kubebuilder:validation:Optional
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// +kubebuilder:validation:Optional
	Services *string `json:"services,omitempty" tf:"services,omitempty"`

	// Limit for services load balancers in project (string)
	// +kubebuilder:validation:Optional
	ServicesLoadBalancers *string `json:"servicesLoadBalancers,omitempty" tf:"services_load_balancers,omitempty"`

	// Limit for services node ports in project (string)
	// +kubebuilder:validation:Optional
	ServicesNodePorts *string `json:"servicesNodePorts,omitempty" tf:"services_node_ports,omitempty"`
}

type ProjectObservation struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id where create project (string)
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Default containers resource limits on project (List maxitem:1)
	ContainerResourceLimit []ContainerResourceLimitObservation `json:"containerResourceLimit,omitempty" tf:"container_resource_limit,omitempty"`

	// A project description (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Resource quota for project. Rancher v2.1.x or higher (list maxitems:1)
	ResourceQuota []ResourceQuotaObservation `json:"resourceQuota,omitempty" tf:"resource_quota,omitempty"`

	// Wait for cluster becomes active. Default false (bool)
	// Wait for cluster becomes active
	WaitForCluster *bool `json:"waitForCluster,omitempty" tf:"wait_for_cluster,omitempty"`
}

type ProjectParameters struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id where create project (string)
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/cluster/cluster/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in cluster to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Default containers resource limits on project (List maxitem:1)
	// +kubebuilder:validation:Optional
	ContainerResourceLimit []ContainerResourceLimitParameters `json:"containerResourceLimit,omitempty" tf:"container_resource_limit,omitempty"`

	// A project description (string)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Resource quota for project. Rancher v2.1.x or higher (list maxitems:1)
	// +kubebuilder:validation:Optional
	ResourceQuota []ResourceQuotaParameters `json:"resourceQuota,omitempty" tf:"resource_quota,omitempty"`

	// Wait for cluster becomes active. Default false (bool)
	// Wait for cluster becomes active
	// +kubebuilder:validation:Optional
	WaitForCluster *bool `json:"waitForCluster,omitempty" tf:"wait_for_cluster,omitempty"`
}

type ResourceQuotaInitParameters struct {

	// Default resource quota limit for  namespaces in project (list maxitems:1)
	NamespaceDefaultLimit []NamespaceDefaultLimitInitParameters `json:"namespaceDefaultLimit,omitempty" tf:"namespace_default_limit,omitempty"`

	// Resource quota limit for project (list maxitems:1)
	ProjectLimit []ProjectLimitInitParameters `json:"projectLimit,omitempty" tf:"project_limit,omitempty"`
}

type ResourceQuotaObservation struct {

	// Default resource quota limit for  namespaces in project (list maxitems:1)
	NamespaceDefaultLimit []NamespaceDefaultLimitObservation `json:"namespaceDefaultLimit,omitempty" tf:"namespace_default_limit,omitempty"`

	// Resource quota limit for project (list maxitems:1)
	ProjectLimit []ProjectLimitObservation `json:"projectLimit,omitempty" tf:"project_limit,omitempty"`
}

type ResourceQuotaParameters struct {

	// Default resource quota limit for  namespaces in project (list maxitems:1)
	// +kubebuilder:validation:Optional
	NamespaceDefaultLimit []NamespaceDefaultLimitParameters `json:"namespaceDefaultLimit" tf:"namespace_default_limit,omitempty"`

	// Resource quota limit for project (list maxitems:1)
	// +kubebuilder:validation:Optional
	ProjectLimit []ProjectLimitParameters `json:"projectLimit" tf:"project_limit,omitempty"`
}

// ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInitParameters `json:"initProvider,omitempty"`
}

// ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Project is the Schema for the Projects API. "Managed resource"page_title: "rancher2_project Resource"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher}
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// Repository type metadata.
var (
	Project_Kind             = "Project"
	Project_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Project_Kind}.String()
	Project_KindAPIVersion   = Project_Kind + "." + CRDGroupVersion.String()
	Project_GroupVersionKind = CRDGroupVersion.WithKind(Project_Kind)
)

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
