// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type V2InitParameters struct {

	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Chart name
	ChartName *string `json:"chartName,omitempty" tf:"chart_name,omitempty"`

	// Chart version
	ChartVersion *string `json:"chartVersion,omitempty" tf:"chart_version,omitempty"`

	// Cleanup app V2 on failed chart upgrade
	CleanupOnFail *bool `json:"cleanupOnFail,omitempty" tf:"cleanup_on_fail,omitempty"`

	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Disable app V2 chart hooks
	DisableHooks *bool `json:"disableHooks,omitempty" tf:"disable_hooks,omitempty"`

	// Disable app V2 Open API Validation
	DisableOpenAPIValidation *bool `json:"disableOpenApiValidation,omitempty" tf:"disable_open_api_validation,omitempty"`

	// Force app V2 chart upgrade
	ForceUpgrade *bool `json:"forceUpgrade,omitempty" tf:"force_upgrade,omitempty"`

	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// App v2 namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Deploy app within project ID
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Repo name
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// System default registry providing images for app deployment.
	SystemDefaultRegistry *string `json:"systemDefaultRegistry,omitempty" tf:"system_default_registry,omitempty"`

	// App v2 custom values yaml
	Values *string `json:"values,omitempty" tf:"values,omitempty"`

	// Wait until app is deployed
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

type V2Observation struct {

	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Chart name
	ChartName *string `json:"chartName,omitempty" tf:"chart_name,omitempty"`

	// Chart version
	ChartVersion *string `json:"chartVersion,omitempty" tf:"chart_version,omitempty"`

	// Cleanup app V2 on failed chart upgrade
	CleanupOnFail *bool `json:"cleanupOnFail,omitempty" tf:"cleanup_on_fail,omitempty"`

	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// Values YAML file including computed values.
	DeploymentValues *string `json:"deploymentValues,omitempty" tf:"deployment_values,omitempty"`

	// Disable app V2 chart hooks
	DisableHooks *bool `json:"disableHooks,omitempty" tf:"disable_hooks,omitempty"`

	// Disable app V2 Open API Validation
	DisableOpenAPIValidation *bool `json:"disableOpenApiValidation,omitempty" tf:"disable_open_api_validation,omitempty"`

	// Force app V2 chart upgrade
	ForceUpgrade *bool `json:"forceUpgrade,omitempty" tf:"force_upgrade,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// App v2 namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Deploy app within project ID
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Repo name
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// System default registry providing images for app deployment.
	SystemDefaultRegistry *string `json:"systemDefaultRegistry,omitempty" tf:"system_default_registry,omitempty"`

	// App v2 custom values yaml
	Values *string `json:"values,omitempty" tf:"values,omitempty"`

	// Wait until app is deployed
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

type V2Parameters struct {

	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Chart name
	// +kubebuilder:validation:Optional
	ChartName *string `json:"chartName,omitempty" tf:"chart_name,omitempty"`

	// Chart version
	// +kubebuilder:validation:Optional
	ChartVersion *string `json:"chartVersion,omitempty" tf:"chart_version,omitempty"`

	// Cleanup app V2 on failed chart upgrade
	// +kubebuilder:validation:Optional
	CleanupOnFail *bool `json:"cleanupOnFail,omitempty" tf:"cleanup_on_fail,omitempty"`

	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Disable app V2 chart hooks
	// +kubebuilder:validation:Optional
	DisableHooks *bool `json:"disableHooks,omitempty" tf:"disable_hooks,omitempty"`

	// Disable app V2 Open API Validation
	// +kubebuilder:validation:Optional
	DisableOpenAPIValidation *bool `json:"disableOpenApiValidation,omitempty" tf:"disable_open_api_validation,omitempty"`

	// Force app V2 chart upgrade
	// +kubebuilder:validation:Optional
	ForceUpgrade *bool `json:"forceUpgrade,omitempty" tf:"force_upgrade,omitempty"`

	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// App v2 namespace
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Deploy app within project ID
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Repo name
	// +kubebuilder:validation:Optional
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// System default registry providing images for app deployment.
	// +kubebuilder:validation:Optional
	SystemDefaultRegistry *string `json:"systemDefaultRegistry,omitempty" tf:"system_default_registry,omitempty"`

	// App v2 custom values yaml
	// +kubebuilder:validation:Optional
	Values *string `json:"values,omitempty" tf:"values,omitempty"`

	// Wait until app is deployed
	// +kubebuilder:validation:Optional
	Wait *bool `json:"wait,omitempty" tf:"wait,omitempty"`
}

// V2Spec defines the desired state of V2
type V2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     V2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider V2InitParameters `json:"initProvider,omitempty"`
}

// V2Status defines the observed state of V2.
type V2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        V2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// V2 is the Schema for the V2s API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher}
type V2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.chartName) || (has(self.initProvider) && has(self.initProvider.chartName))",message="spec.forProvider.chartName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repoName) || (has(self.initProvider) && has(self.initProvider.repoName))",message="spec.forProvider.repoName is a required parameter"
	Spec   V2Spec   `json:"spec"`
	Status V2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// V2List contains a list of V2s
type V2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []V2 `json:"items"`
}

// Repository type metadata.
var (
	V2_Kind             = "V2"
	V2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: V2_Kind}.String()
	V2_KindAPIVersion   = V2_Kind + "." + CRDGroupVersion.String()
	V2_GroupVersionKind = CRDGroupVersion.WithKind(V2_Kind)
)

func init() {
	SchemeBuilder.Register(&V2{}, &V2List{})
}
