apiVersion: project.rancher.m.openplatform.suse.com/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    clusterId: <CLUSTER_ID>
    containerResourceLimit:
    - limitsCpu: 20m
      limitsMemory: 20Mi
      requestsCpu: 1m
      requestsMemory: 1Mi
    resourceQuota:
    - namespaceDefaultLimit:
      - limitsCpu: 2000m
        limitsMemory: 500Mi
        requestsStorage: 1Gi
      projectLimit:
      - limitsCpu: 2000m
        limitsMemory: 2000Mi
        requestsStorage: 2Gi
