// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProjectRoleTemplateBindingInitParameters struct {

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The group ID to assign project role template binding (string)
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The group_principal ID to assign project role template binding (string)
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The project id where bind project role template, in format cluster_id:project_id, e.g. c-abc12:p-def34 (string)
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/namespaced/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The role template id from create project role template binding (string)
	RoleTemplateID *string `json:"roleTemplateId,omitempty" tf:"role_template_id,omitempty"`

	// The user ID to assign project role template binding (string)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The user_principal ID to assign project role template binding (string)
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

type ProjectRoleTemplateBindingObservation struct {

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The group ID to assign project role template binding (string)
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The group_principal ID to assign project role template binding (string)
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The project id where bind project role template, in format cluster_id:project_id, e.g. c-abc12:p-def34 (string)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// The role template id from create project role template binding (string)
	RoleTemplateID *string `json:"roleTemplateId,omitempty" tf:"role_template_id,omitempty"`

	// The user ID to assign project role template binding (string)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The user_principal ID to assign project role template binding (string)
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

type ProjectRoleTemplateBindingParameters struct {

	// Annotations of the resource (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The group ID to assign project role template binding (string)
	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The group_principal ID to assign project role template binding (string)
	// +kubebuilder:validation:Optional
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The project id where bind project role template, in format cluster_id:project_id, e.g. c-abc12:p-def34 (string)
	// +crossplane:generate:reference:type=github.com/tmuntaner/provider-rancher/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// The role template id from create project role template binding (string)
	// +kubebuilder:validation:Optional
	RoleTemplateID *string `json:"roleTemplateId,omitempty" tf:"role_template_id,omitempty"`

	// The user ID to assign project role template binding (string)
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The user_principal ID to assign project role template binding (string)
	// +kubebuilder:validation:Optional
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

// ProjectRoleTemplateBindingSpec defines the desired state of ProjectRoleTemplateBinding
type ProjectRoleTemplateBindingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectRoleTemplateBindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectRoleTemplateBindingInitParameters `json:"initProvider,omitempty"`
}

// ProjectRoleTemplateBindingStatus defines the observed state of ProjectRoleTemplateBinding.
type ProjectRoleTemplateBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectRoleTemplateBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectRoleTemplateBinding is the Schema for the ProjectRoleTemplateBindings API. "Managed resource"page_title: "rancher2_project_role_template_binding Resource"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher}
type ProjectRoleTemplateBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleTemplateId) || (has(self.initProvider) && has(self.initProvider.roleTemplateId))",message="spec.forProvider.roleTemplateId is a required parameter"
	Spec   ProjectRoleTemplateBindingSpec   `json:"spec"`
	Status ProjectRoleTemplateBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectRoleTemplateBindingList contains a list of ProjectRoleTemplateBindings
type ProjectRoleTemplateBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectRoleTemplateBinding `json:"items"`
}

// Repository type metadata.
var (
	ProjectRoleTemplateBinding_Kind             = "ProjectRoleTemplateBinding"
	ProjectRoleTemplateBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectRoleTemplateBinding_Kind}.String()
	ProjectRoleTemplateBinding_KindAPIVersion   = ProjectRoleTemplateBinding_Kind + "." + CRDGroupVersion.String()
	ProjectRoleTemplateBinding_GroupVersionKind = CRDGroupVersion.WithKind(ProjectRoleTemplateBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectRoleTemplateBinding{}, &ProjectRoleTemplateBindingList{})
}
